/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f73193f7cdb9491eae538c6636d8bb4d)
interface __BaseEnv_Env {
	AI: Ai;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	NotesStore: DurableObjectNamespace<import("./src/server").NotesStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "NotesStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
