/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 14ea06cf01f9fb708b87318f6d070cde)
interface __BaseEnv_Env {
	AI: Ai;
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	NotesStore: DurableObjectNamespace<import("./src/server/worker").NotesStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/worker");
		durableNamespaces: "NotesStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY">> {}
}
